//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmendmentFilterLevelOfDetailType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AmendmentFilterLevelOfDetailType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AmendedOrderSummary"/&gt;
 *     &lt;enumeration value="AmendmentsSummary"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AmendmentFilterLevelOfDetailType")
@XmlEnum
public enum AmendmentFilterLevelOfDetailType {

    @XmlEnumValue("AmendedOrderSummary")
    AMENDED_ORDER_SUMMARY("AmendedOrderSummary"),
    @XmlEnumValue("AmendmentsSummary")
    AMENDMENTS_SUMMARY("AmendmentsSummary");
    private final String value;

    AmendmentFilterLevelOfDetailType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AmendmentFilterLevelOfDetailType fromValue(String v) {
        for (AmendmentFilterLevelOfDetailType c: AmendmentFilterLevelOfDetailType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
