//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmendmentStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AmendmentStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="accepted"/&gt;
 *     &lt;enumeration value="queued"/&gt;
 *     &lt;enumeration value="in_progress"/&gt;
 *     &lt;enumeration value="skipped"/&gt;
 *     &lt;enumeration value="completed"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AmendmentStatusType")
@XmlEnum
public enum AmendmentStatusType {

    @XmlEnumValue("accepted")
    ACCEPTED("accepted"),
    @XmlEnumValue("queued")
    QUEUED("queued"),
    @XmlEnumValue("in_progress")
    IN_PROGRESS("in_progress"),
    @XmlEnumValue("skipped")
    SKIPPED("skipped"),
    @XmlEnumValue("completed")
    COMPLETED("completed");
    private final String value;

    AmendmentStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AmendmentStatusType fromValue(String v) {
        for (AmendmentStatusType c: AmendmentStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
