//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.activation.DataHandler;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttachmentRef;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *     Defines a file that has been attached
 *                 to a remark.
 * 
 * <p>Java class for AttachmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttachmentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://xmlns.oracle.com/communications/ordermanagement}NonEmptyNormalizedStringType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="swaRefMimeContent" type="{http://ws-i.org/profiles/basic/1.1/xsd}swaRef"/&gt;
 *           &lt;element name="base64BinaryContent" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *           &lt;element name="hexBinaryContent" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttachmentType", propOrder = {
    "name",
    "swaRefMimeContent",
    "base64BinaryContent",
    "hexBinaryContent"
})
public class AttachmentType {

    @XmlElement(name = "Name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String name;
    @XmlElement(type = String.class)
    @XmlAttachmentRef
    @XmlSchemaType(name = "anyURI")
    protected DataHandler swaRefMimeContent;
    protected byte[] base64BinaryContent;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] hexBinaryContent;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the swaRefMimeContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DataHandler getSwaRefMimeContent() {
        return swaRefMimeContent;
    }

    /**
     * Sets the value of the swaRefMimeContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwaRefMimeContent(DataHandler value) {
        this.swaRefMimeContent = value;
    }

    /**
     * Gets the value of the base64BinaryContent property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBase64BinaryContent() {
        return base64BinaryContent;
    }

    /**
     * Sets the value of the base64BinaryContent property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBase64BinaryContent(byte[] value) {
        this.base64BinaryContent = value;
    }

    /**
     * Gets the value of the hexBinaryContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getHexBinaryContent() {
        return hexBinaryContent;
    }

    /**
     * Sets the value of the hexBinaryContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHexBinaryContent(byte[] value) {
        this.hexBinaryContent = value;
    }

}
