//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *     A summary of the created order.
 * 
 * <p>Java class for CreateOrderBySpecificationResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateOrderBySpecificationResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderSummary" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderSummaryType"/&gt;
 *         &lt;element name="AmendmentSummary" type="{http://xmlns.oracle.com/communications/ordermanagement}AmendmentSummaryType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateOrderBySpecificationResponseType", propOrder = {
    "orderSummary",
    "amendmentSummary"
})
public class CreateOrderBySpecificationResponseType {

    @XmlElement(name = "OrderSummary", required = true)
    protected OrderSummaryType orderSummary;
    @XmlElement(name = "AmendmentSummary")
    protected AmendmentSummaryType amendmentSummary;

    /**
     * Gets the value of the orderSummary property.
     * 
     * @return
     *     possible object is
     *     {@link OrderSummaryType }
     *     
     */
    public OrderSummaryType getOrderSummary() {
        return orderSummary;
    }

    /**
     * Sets the value of the orderSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderSummaryType }
     *     
     */
    public void setOrderSummary(OrderSummaryType value) {
        this.orderSummary = value;
    }

    /**
     * Gets the value of the amendmentSummary property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentSummaryType }
     *     
     */
    public AmendmentSummaryType getAmendmentSummary() {
        return amendmentSummary;
    }

    /**
     * Sets the value of the amendmentSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentSummaryType }
     *     
     */
    public void setAmendmentSummary(AmendmentSummaryType value) {
        this.amendmentSummary = value;
    }

}
