//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateOrderBySpecificationRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateOrderBySpecificationRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Specification" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderSpecificationType"/&gt;
 *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Priority" type="{http://xmlns.oracle.com/communications/ordermanagement}PriorityType" minOccurs="0"/&gt;
 *         &lt;element name="AutoAddMandatoryData" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="StartOrder" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="Data" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderDataType" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="Remark" type="{http://xmlns.oracle.com/communications/ordermanagement}CreateRemarkType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateOrderBySpecificationRequestType", propOrder = {
    "specification",
    "reference",
    "priority",
    "autoAddMandatoryData",
    "startOrder",
    "data",
    "remark"
})
public class CreateOrderBySpecificationRequestType {

    @XmlElement(name = "Specification", required = true)
    protected OrderSpecificationType specification;
    @XmlElement(name = "Reference")
    protected String reference;
    @XmlElement(name = "Priority", defaultValue = "5")
    protected Integer priority;
    @XmlElement(name = "AutoAddMandatoryData", defaultValue = "false")
    protected Boolean autoAddMandatoryData;
    @XmlElement(name = "StartOrder", defaultValue = "true")
    protected Boolean startOrder;
    @XmlElement(name = "Data")
    protected OrderDataType data;
    @XmlElement(name = "Remark")
    protected List<CreateRemarkType> remark;

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link OrderSpecificationType }
     *     
     */
    public OrderSpecificationType getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderSpecificationType }
     *     
     */
    public void setSpecification(OrderSpecificationType value) {
        this.specification = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the autoAddMandatoryData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoAddMandatoryData() {
        return autoAddMandatoryData;
    }

    /**
     * Sets the value of the autoAddMandatoryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoAddMandatoryData(Boolean value) {
        this.autoAddMandatoryData = value;
    }

    /**
     * Gets the value of the startOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStartOrder() {
        return startOrder;
    }

    /**
     * Sets the value of the startOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStartOrder(Boolean value) {
        this.startOrder = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDataType }
     *     
     */
    public OrderDataType getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDataType }
     *     
     */
    public void setData(OrderDataType value) {
        this.data = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemark().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreateRemarkType }
     * 
     * 
     */
    public List<CreateRemarkType> getRemark() {
        if (remark == null) {
            remark = new ArrayList<CreateRemarkType>();
        }
        return this.remark;
    }

}
