//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Results that satisfy the selector
 *                 conditions from a FindOrder request.
 * 
 * <p>Java class for FindOrderResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindOrderResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Order" type="{http://xmlns.oracle.com/communications/ordermanagement}GetOrderResponseType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="OffsetOrder" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="OrderCount" type="{http://xmlns.oracle.com/communications/ordermanagement}nonNegativeInt" minOccurs="0"/&gt;
 *         &lt;element name="TotalOrders" type="{http://xmlns.oracle.com/communications/ordermanagement}nonNegativeInt" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindOrderResponseType", propOrder = {
    "order",
    "offsetOrder",
    "orderCount",
    "totalOrders"
})
public class FindOrderResponseType {

    @XmlElement(name = "Order")
    protected List<GetOrderResponseType> order;
    @XmlElement(name = "OffsetOrder", defaultValue = "0")
    protected Integer offsetOrder;
    @XmlElement(name = "OrderCount")
    protected Integer orderCount;
    @XmlElement(name = "TotalOrders")
    protected Integer totalOrders;

    /**
     * Gets the value of the order property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the order property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetOrderResponseType }
     * 
     * 
     */
    public List<GetOrderResponseType> getOrder() {
        if (order == null) {
            order = new ArrayList<GetOrderResponseType>();
        }
        return this.order;
    }

    /**
     * Gets the value of the offsetOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOffsetOrder() {
        return offsetOrder;
    }

    /**
     * Sets the value of the offsetOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOffsetOrder(Integer value) {
        this.offsetOrder = value;
    }

    /**
     * Gets the value of the orderCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrderCount() {
        return orderCount;
    }

    /**
     * Sets the value of the orderCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrderCount(Integer value) {
        this.orderCount = value;
    }

    /**
     * Gets the value of the totalOrders property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalOrders() {
        return totalOrders;
    }

    /**
     * Sets the value of the totalOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalOrders(Integer value) {
        this.totalOrders = value;
    }

}
