//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FindOrderRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindOrderRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ViewBy" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="View" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="RemarkFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}RemarkFilter" minOccurs="0"/&gt;
 *                   &lt;element name="AmendmentFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}AmendmentFilterType" minOccurs="0"/&gt;
 *                   &lt;element name="LifecycleEventFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderLifecycleEventFilterType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SelectBy" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="HasFailure" type="{http://xmlns.oracle.com/communications/ordermanagement}HasFailureType" minOccurs="0"/&gt;
 *                   &lt;element name="OrderId" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderIdType" minOccurs="0"/&gt;
 *                   &lt;element name="OrderState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="TargetOrderState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
 *                   &lt;element name="OrderType" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType" minOccurs="0"/&gt;
 *                   &lt;element name="OrderSource" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType" minOccurs="0"/&gt;
 *                   &lt;element name="CreatedDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
 *                   &lt;element name="CompletedDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
 *                   &lt;element name="ExpectedStartDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
 *                   &lt;element name="ExpectedOrderCompletionDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
 *                   &lt;element name="RequestedDeliveryDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
 *                   &lt;element name="ExpectedDuration" type="{http://xmlns.oracle.com/communications/ordermanagement}DurationRangeType" minOccurs="0"/&gt;
 *                   &lt;element name="Priority" type="{http://xmlns.oracle.com/communications/ordermanagement}PriorityType" minOccurs="0"/&gt;
 *                   &lt;element name="Field" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
 *                             &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *                             &lt;choice&gt;
 *                               &lt;element name="EqualTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                               &lt;sequence&gt;
 *                                 &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                 &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                               &lt;/sequence&gt;
 *                               &lt;element name="InList"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                             &lt;/choice&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="OffsetOrder" type="{http://xmlns.oracle.com/communications/ordermanagement}nonNegativeInt" minOccurs="0"/&gt;
 *                   &lt;element name="MaxOrders" type="{http://xmlns.oracle.com/communications/ordermanagement}nonNegativeInt" minOccurs="0"/&gt;
 *                   &lt;element name="ReturnTotalOrders" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OrderBy" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="OrderField" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="SortBy" minOccurs="0"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="Ascending"/&gt;
 *                                   &lt;enumeration value="Descending"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Header" minOccurs="0"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="CompletedDate"/&gt;
 *                                   &lt;enumeration value="CreatedDate"/&gt;
 *                                   &lt;enumeration value="ExpectedOrderCompletionDate"/&gt;
 *                                   &lt;enumeration value="ExpectedStartDate"/&gt;
 *                                   &lt;enumeration value="ExpectedDuration"/&gt;
 *                                   &lt;enumeration value="OrderId"/&gt;
 *                                   &lt;enumeration value="OrderKey"/&gt;
 *                                   &lt;enumeration value="OrderSource"/&gt;
 *                                   &lt;enumeration value="OrderState"/&gt;
 *                                   &lt;enumeration value="OrderType"/&gt;
 *                                   &lt;enumeration value="Priority"/&gt;
 *                                   &lt;enumeration value="Reference"/&gt;
 *                                   &lt;enumeration value="RequestedDeliveryDate"/&gt;
 *                                   &lt;enumeration value="TargetOrderState"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Field" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
 *                                       &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindOrderRequestType", propOrder = {
    "viewBy",
    "selectBy",
    "orderBy"
})
public class FindOrderRequestType {

    @XmlElement(name = "ViewBy")
    protected ViewBy viewBy;
    @XmlElement(name = "SelectBy")
    protected SelectBy selectBy;
    @XmlElement(name = "OrderBy")
    protected OrderBy orderBy;

    /**
     * Gets the value of the viewBy property.
     * 
     * @return
     *     possible object is
     *     {@link ViewBy }
     *     
     */
    public ViewBy getViewBy() {
        return viewBy;
    }

    /**
     * Sets the value of the viewBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewBy }
     *     
     */
    public void setViewBy(ViewBy value) {
        this.viewBy = value;
    }

    /**
     * Gets the value of the selectBy property.
     * 
     * @return
     *     possible object is
     *     {@link SelectBy }
     *     
     */
    public SelectBy getSelectBy() {
        return selectBy;
    }

    /**
     * Sets the value of the selectBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectBy }
     *     
     */
    public void setSelectBy(SelectBy value) {
        this.selectBy = value;
    }

    /**
     * Gets the value of the orderBy property.
     * 
     * @return
     *     possible object is
     *     {@link OrderBy }
     *     
     */
    public OrderBy getOrderBy() {
        return orderBy;
    }

    /**
     * Sets the value of the orderBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderBy }
     *     
     */
    public void setOrderBy(OrderBy value) {
        this.orderBy = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="OrderField" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="SortBy" minOccurs="0"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="Ascending"/&gt;
     *                         &lt;enumeration value="Descending"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Header" minOccurs="0"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="CompletedDate"/&gt;
     *                         &lt;enumeration value="CreatedDate"/&gt;
     *                         &lt;enumeration value="ExpectedOrderCompletionDate"/&gt;
     *                         &lt;enumeration value="ExpectedStartDate"/&gt;
     *                         &lt;enumeration value="ExpectedDuration"/&gt;
     *                         &lt;enumeration value="OrderId"/&gt;
     *                         &lt;enumeration value="OrderKey"/&gt;
     *                         &lt;enumeration value="OrderSource"/&gt;
     *                         &lt;enumeration value="OrderState"/&gt;
     *                         &lt;enumeration value="OrderType"/&gt;
     *                         &lt;enumeration value="Priority"/&gt;
     *                         &lt;enumeration value="Reference"/&gt;
     *                         &lt;enumeration value="RequestedDeliveryDate"/&gt;
     *                         &lt;enumeration value="TargetOrderState"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Field" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
     *                             &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderField"
    })
    public static class OrderBy {

        @XmlElement(name = "OrderField", required = true)
        protected List<OrderField> orderField;

        /**
         * Gets the value of the orderField property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orderField property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrderField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderField }
         * 
         * 
         */
        public List<OrderField> getOrderField() {
            if (orderField == null) {
                orderField = new ArrayList<OrderField>();
            }
            return this.orderField;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="SortBy" minOccurs="0"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="Ascending"/&gt;
         *               &lt;enumeration value="Descending"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Header" minOccurs="0"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="CompletedDate"/&gt;
         *               &lt;enumeration value="CreatedDate"/&gt;
         *               &lt;enumeration value="ExpectedOrderCompletionDate"/&gt;
         *               &lt;enumeration value="ExpectedStartDate"/&gt;
         *               &lt;enumeration value="ExpectedDuration"/&gt;
         *               &lt;enumeration value="OrderId"/&gt;
         *               &lt;enumeration value="OrderKey"/&gt;
         *               &lt;enumeration value="OrderSource"/&gt;
         *               &lt;enumeration value="OrderState"/&gt;
         *               &lt;enumeration value="OrderType"/&gt;
         *               &lt;enumeration value="Priority"/&gt;
         *               &lt;enumeration value="Reference"/&gt;
         *               &lt;enumeration value="RequestedDeliveryDate"/&gt;
         *               &lt;enumeration value="TargetOrderState"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Field" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
         *                   &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sortBy",
            "header",
            "field"
        })
        public static class OrderField {

            @XmlElement(name = "SortBy")
            protected String sortBy;
            @XmlElement(name = "Header")
            protected String header;
            @XmlElement(name = "Field")
            protected Field field;

            /**
             * Gets the value of the sortBy property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSortBy() {
                return sortBy;
            }

            /**
             * Sets the value of the sortBy property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSortBy(String value) {
                this.sortBy = value;
            }

            /**
             * Gets the value of the header property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHeader() {
                return header;
            }

            /**
             * Sets the value of the header property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHeader(String value) {
                this.header = value;
            }

            /**
             * Gets the value of the field property.
             * 
             * @return
             *     possible object is
             *     {@link Field }
             *     
             */
            public Field getField() {
                return field;
            }

            /**
             * Sets the value of the field property.
             * 
             * @param value
             *     allowed object is
             *     {@link Field }
             *     
             */
            public void setField(Field value) {
                this.field = value;
            }


            /**
             * Allows
             *                                     orders to be sorted
             *                                     by flexible header values.
             * 
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
             *         &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cartridge",
                "path"
            })
            public static class Field {

                @XmlElement(name = "Cartridge")
                protected CartridgeType cartridge;
                @XmlElement(name = "Path", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String path;

                /**
                 * Gets the value of the cartridge property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CartridgeType }
                 *     
                 */
                public CartridgeType getCartridge() {
                    return cartridge;
                }

                /**
                 * Sets the value of the cartridge property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CartridgeType }
                 *     
                 */
                public void setCartridge(CartridgeType value) {
                    this.cartridge = value;
                }

                /**
                 * Gets the value of the path property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPath() {
                    return path;
                }

                /**
                 * Sets the value of the path property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPath(String value) {
                    this.path = value;
                }

            }

        }

    }


    /**
     * Specifies a set of criteria
     *                             used to filter the result set of orders
     *                             returned by the FindOrder operation.
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="HasFailure" type="{http://xmlns.oracle.com/communications/ordermanagement}HasFailureType" minOccurs="0"/&gt;
     *         &lt;element name="OrderId" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderIdType" minOccurs="0"/&gt;
     *         &lt;element name="OrderState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="TargetOrderState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
     *         &lt;element name="OrderType" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType" minOccurs="0"/&gt;
     *         &lt;element name="OrderSource" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType" minOccurs="0"/&gt;
     *         &lt;element name="CreatedDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
     *         &lt;element name="CompletedDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
     *         &lt;element name="ExpectedStartDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
     *         &lt;element name="ExpectedOrderCompletionDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
     *         &lt;element name="RequestedDeliveryDate" type="{http://xmlns.oracle.com/communications/ordermanagement}DateRangeType" minOccurs="0"/&gt;
     *         &lt;element name="ExpectedDuration" type="{http://xmlns.oracle.com/communications/ordermanagement}DurationRangeType" minOccurs="0"/&gt;
     *         &lt;element name="Priority" type="{http://xmlns.oracle.com/communications/ordermanagement}PriorityType" minOccurs="0"/&gt;
     *         &lt;element name="Field" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
     *                   &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
     *                   &lt;choice&gt;
     *                     &lt;element name="EqualTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                     &lt;sequence&gt;
     *                       &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                       &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                     &lt;/sequence&gt;
     *                     &lt;element name="InList"&gt;
     *                       &lt;complexType&gt;
     *                         &lt;complexContent&gt;
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                             &lt;sequence&gt;
     *                               &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                             &lt;/sequence&gt;
     *                           &lt;/restriction&gt;
     *                         &lt;/complexContent&gt;
     *                       &lt;/complexType&gt;
     *                     &lt;/element&gt;
     *                   &lt;/choice&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="OffsetOrder" type="{http://xmlns.oracle.com/communications/ordermanagement}nonNegativeInt" minOccurs="0"/&gt;
     *         &lt;element name="MaxOrders" type="{http://xmlns.oracle.com/communications/ordermanagement}nonNegativeInt" minOccurs="0"/&gt;
     *         &lt;element name="ReturnTotalOrders" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hasFailure",
        "orderId",
        "orderState",
        "targetOrderState",
        "reference",
        "cartridge",
        "orderType",
        "orderSource",
        "createdDate",
        "completedDate",
        "expectedStartDate",
        "expectedOrderCompletionDate",
        "requestedDeliveryDate",
        "expectedDuration",
        "priority",
        "field",
        "offsetOrder",
        "maxOrders",
        "returnTotalOrders"
    })
    public static class SelectBy {

        @XmlElement(name = "HasFailure")
        protected Boolean hasFailure;
        @XmlElement(name = "OrderId")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String orderId;
        @XmlElement(name = "OrderState")
        @XmlSchemaType(name = "string")
        protected List<OrderStateType> orderState;
        @XmlElement(name = "TargetOrderState")
        @XmlSchemaType(name = "string")
        protected List<OrderStateType> targetOrderState;
        @XmlElement(name = "Reference")
        protected String reference;
        @XmlElement(name = "Cartridge")
        protected CartridgeType cartridge;
        @XmlElement(name = "OrderType")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String orderType;
        @XmlElement(name = "OrderSource")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String orderSource;
        @XmlElement(name = "CreatedDate")
        protected DateRangeType createdDate;
        @XmlElement(name = "CompletedDate")
        protected DateRangeType completedDate;
        @XmlElement(name = "ExpectedStartDate")
        protected DateRangeType expectedStartDate;
        @XmlElement(name = "ExpectedOrderCompletionDate")
        protected DateRangeType expectedOrderCompletionDate;
        @XmlElement(name = "RequestedDeliveryDate")
        protected DateRangeType requestedDeliveryDate;
        @XmlElement(name = "ExpectedDuration")
        protected DurationRangeType expectedDuration;
        @XmlElement(name = "Priority")
        protected Integer priority;
        @XmlElement(name = "Field")
        protected List<Field> field;
        @XmlElement(name = "OffsetOrder", defaultValue = "0")
        protected Integer offsetOrder;
        @XmlElement(name = "MaxOrders")
        protected Integer maxOrders;
        @XmlElement(name = "ReturnTotalOrders", defaultValue = "false")
        protected Boolean returnTotalOrders;

        /**
         * Gets the value of the hasFailure property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isHasFailure() {
            return hasFailure;
        }

        /**
         * Sets the value of the hasFailure property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setHasFailure(Boolean value) {
            this.hasFailure = value;
        }

        /**
         * Gets the value of the orderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderId() {
            return orderId;
        }

        /**
         * Sets the value of the orderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderId(String value) {
            this.orderId = value;
        }

        /**
         * Gets the value of the orderState property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orderState property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrderState().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderStateType }
         * 
         * 
         */
        public List<OrderStateType> getOrderState() {
            if (orderState == null) {
                orderState = new ArrayList<OrderStateType>();
            }
            return this.orderState;
        }

        /**
         * Gets the value of the targetOrderState property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the targetOrderState property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTargetOrderState().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderStateType }
         * 
         * 
         */
        public List<OrderStateType> getTargetOrderState() {
            if (targetOrderState == null) {
                targetOrderState = new ArrayList<OrderStateType>();
            }
            return this.targetOrderState;
        }

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReference(String value) {
            this.reference = value;
        }

        /**
         * Gets the value of the cartridge property.
         * 
         * @return
         *     possible object is
         *     {@link CartridgeType }
         *     
         */
        public CartridgeType getCartridge() {
            return cartridge;
        }

        /**
         * Sets the value of the cartridge property.
         * 
         * @param value
         *     allowed object is
         *     {@link CartridgeType }
         *     
         */
        public void setCartridge(CartridgeType value) {
            this.cartridge = value;
        }

        /**
         * Gets the value of the orderType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderType() {
            return orderType;
        }

        /**
         * Sets the value of the orderType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderType(String value) {
            this.orderType = value;
        }

        /**
         * Gets the value of the orderSource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderSource() {
            return orderSource;
        }

        /**
         * Sets the value of the orderSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderSource(String value) {
            this.orderSource = value;
        }

        /**
         * Gets the value of the createdDate property.
         * 
         * @return
         *     possible object is
         *     {@link DateRangeType }
         *     
         */
        public DateRangeType getCreatedDate() {
            return createdDate;
        }

        /**
         * Sets the value of the createdDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateRangeType }
         *     
         */
        public void setCreatedDate(DateRangeType value) {
            this.createdDate = value;
        }

        /**
         * Gets the value of the completedDate property.
         * 
         * @return
         *     possible object is
         *     {@link DateRangeType }
         *     
         */
        public DateRangeType getCompletedDate() {
            return completedDate;
        }

        /**
         * Sets the value of the completedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateRangeType }
         *     
         */
        public void setCompletedDate(DateRangeType value) {
            this.completedDate = value;
        }

        /**
         * Gets the value of the expectedStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link DateRangeType }
         *     
         */
        public DateRangeType getExpectedStartDate() {
            return expectedStartDate;
        }

        /**
         * Sets the value of the expectedStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateRangeType }
         *     
         */
        public void setExpectedStartDate(DateRangeType value) {
            this.expectedStartDate = value;
        }

        /**
         * Gets the value of the expectedOrderCompletionDate property.
         * 
         * @return
         *     possible object is
         *     {@link DateRangeType }
         *     
         */
        public DateRangeType getExpectedOrderCompletionDate() {
            return expectedOrderCompletionDate;
        }

        /**
         * Sets the value of the expectedOrderCompletionDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateRangeType }
         *     
         */
        public void setExpectedOrderCompletionDate(DateRangeType value) {
            this.expectedOrderCompletionDate = value;
        }

        /**
         * Gets the value of the requestedDeliveryDate property.
         * 
         * @return
         *     possible object is
         *     {@link DateRangeType }
         *     
         */
        public DateRangeType getRequestedDeliveryDate() {
            return requestedDeliveryDate;
        }

        /**
         * Sets the value of the requestedDeliveryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateRangeType }
         *     
         */
        public void setRequestedDeliveryDate(DateRangeType value) {
            this.requestedDeliveryDate = value;
        }

        /**
         * Gets the value of the expectedDuration property.
         * 
         * @return
         *     possible object is
         *     {@link DurationRangeType }
         *     
         */
        public DurationRangeType getExpectedDuration() {
            return expectedDuration;
        }

        /**
         * Sets the value of the expectedDuration property.
         * 
         * @param value
         *     allowed object is
         *     {@link DurationRangeType }
         *     
         */
        public void setExpectedDuration(DurationRangeType value) {
            this.expectedDuration = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPriority(Integer value) {
            this.priority = value;
        }

        /**
         * Gets the value of the field property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the field property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Field }
         * 
         * 
         */
        public List<Field> getField() {
            if (field == null) {
                field = new ArrayList<Field>();
            }
            return this.field;
        }

        /**
         * Gets the value of the offsetOrder property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getOffsetOrder() {
            return offsetOrder;
        }

        /**
         * Sets the value of the offsetOrder property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setOffsetOrder(Integer value) {
            this.offsetOrder = value;
        }

        /**
         * Gets the value of the maxOrders property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMaxOrders() {
            return maxOrders;
        }

        /**
         * Sets the value of the maxOrders property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMaxOrders(Integer value) {
            this.maxOrders = value;
        }

        /**
         * Gets the value of the returnTotalOrders property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isReturnTotalOrders() {
            return returnTotalOrders;
        }

        /**
         * Sets the value of the returnTotalOrders property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setReturnTotalOrders(Boolean value) {
            this.returnTotalOrders = value;
        }


        /**
         * Allows orders to
         *                                     be retrieved by fixed or flex
         *                                     header values.
         * 
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType" minOccurs="0"/&gt;
         *         &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
         *         &lt;choice&gt;
         *           &lt;element name="EqualTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *           &lt;sequence&gt;
         *             &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *             &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *           &lt;/sequence&gt;
         *           &lt;element name="InList"&gt;
         *             &lt;complexType&gt;
         *               &lt;complexContent&gt;
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                   &lt;sequence&gt;
         *                     &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *                   &lt;/sequence&gt;
         *                 &lt;/restriction&gt;
         *               &lt;/complexContent&gt;
         *             &lt;/complexType&gt;
         *           &lt;/element&gt;
         *         &lt;/choice&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cartridge",
            "path",
            "equalTo",
            "from",
            "to",
            "inList"
        })
        public static class Field {

            @XmlElement(name = "Cartridge")
            protected CartridgeType cartridge;
            @XmlElement(name = "Path", required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String path;
            @XmlElement(name = "EqualTo")
            protected String equalTo;
            @XmlElement(name = "From")
            protected String from;
            @XmlElement(name = "To")
            protected String to;
            @XmlElement(name = "InList")
            protected InList inList;

            /**
             * Gets the value of the cartridge property.
             * 
             * @return
             *     possible object is
             *     {@link CartridgeType }
             *     
             */
            public CartridgeType getCartridge() {
                return cartridge;
            }

            /**
             * Sets the value of the cartridge property.
             * 
             * @param value
             *     allowed object is
             *     {@link CartridgeType }
             *     
             */
            public void setCartridge(CartridgeType value) {
                this.cartridge = value;
            }

            /**
             * Gets the value of the path property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPath() {
                return path;
            }

            /**
             * Sets the value of the path property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPath(String value) {
                this.path = value;
            }

            /**
             * Gets the value of the equalTo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEqualTo() {
                return equalTo;
            }

            /**
             * Sets the value of the equalTo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEqualTo(String value) {
                this.equalTo = value;
            }

            /**
             * Gets the value of the from property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFrom(String value) {
                this.from = value;
            }

            /**
             * Gets the value of the to property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTo(String value) {
                this.to = value;
            }

            /**
             * Gets the value of the inList property.
             * 
             * @return
             *     possible object is
             *     {@link InList }
             *     
             */
            public InList getInList() {
                return inList;
            }

            /**
             * Sets the value of the inList property.
             * 
             * @param value
             *     allowed object is
             *     {@link InList }
             *     
             */
            public void setInList(InList value) {
                this.inList = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class InList {

                @XmlElement(name = "Value", required = true)
                protected List<String> value;

                /**
                 * Gets the value of the value property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the value property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getValue().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getValue() {
                    if (value == null) {
                        value = new ArrayList<String>();
                    }
                    return this.value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="View" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="RemarkFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}RemarkFilter" minOccurs="0"/&gt;
     *         &lt;element name="AmendmentFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}AmendmentFilterType" minOccurs="0"/&gt;
     *         &lt;element name="LifecycleEventFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderLifecycleEventFilterType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "view",
        "remarkFilter",
        "amendmentFilter",
        "lifecycleEventFilter"
    })
    public static class ViewBy {

        @XmlElement(name = "View")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected List<String> view;
        @XmlElement(name = "RemarkFilter")
        protected RemarkFilter remarkFilter;
        @XmlElement(name = "AmendmentFilter")
        protected AmendmentFilterType amendmentFilter;
        @XmlElement(name = "LifecycleEventFilter")
        protected OrderLifecycleEventFilterType lifecycleEventFilter;

        /**
         * Gets the value of the view property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the view property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getView().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getView() {
            if (view == null) {
                view = new ArrayList<String>();
            }
            return this.view;
        }

        /**
         * Gets the value of the remarkFilter property.
         * 
         * @return
         *     possible object is
         *     {@link RemarkFilter }
         *     
         */
        public RemarkFilter getRemarkFilter() {
            return remarkFilter;
        }

        /**
         * Sets the value of the remarkFilter property.
         * 
         * @param value
         *     allowed object is
         *     {@link RemarkFilter }
         *     
         */
        public void setRemarkFilter(RemarkFilter value) {
            this.remarkFilter = value;
        }

        /**
         * Gets the value of the amendmentFilter property.
         * 
         * @return
         *     possible object is
         *     {@link AmendmentFilterType }
         *     
         */
        public AmendmentFilterType getAmendmentFilter() {
            return amendmentFilter;
        }

        /**
         * Sets the value of the amendmentFilter property.
         * 
         * @param value
         *     allowed object is
         *     {@link AmendmentFilterType }
         *     
         */
        public void setAmendmentFilter(AmendmentFilterType value) {
            this.amendmentFilter = value;
        }

        /**
         * Gets the value of the lifecycleEventFilter property.
         * 
         * @return
         *     possible object is
         *     {@link OrderLifecycleEventFilterType }
         *     
         */
        public OrderLifecycleEventFilterType getLifecycleEventFilter() {
            return lifecycleEventFilter;
        }

        /**
         * Sets the value of the lifecycleEventFilter property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderLifecycleEventFilterType }
         *     
         */
        public void setLifecycleEventFilter(OrderLifecycleEventFilterType value) {
            this.lifecycleEventFilter = value;
        }

    }

}
