//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetOrderResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetOrderResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderSummary" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderSummaryType"/&gt;
 *         &lt;element name="Data" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderDataType" minOccurs="0"/&gt;
 *         &lt;element name="Remarks" type="{http://xmlns.oracle.com/communications/ordermanagement}RemarksType" minOccurs="0"/&gt;
 *         &lt;element name="Amendments" type="{http://xmlns.oracle.com/communications/ordermanagement}AmendmentsType" minOccurs="0"/&gt;
 *         &lt;element name="LifecycleEvents" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderLifecycleEvents" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetOrderResponseType", propOrder = {
    "orderSummary",
    "data",
    "remarks",
    "amendments",
    "lifecycleEvents"
})
public class GetOrderResponseType {

    @XmlElement(name = "OrderSummary", required = true)
    protected OrderSummaryType orderSummary;
    @XmlElement(name = "Data")
    protected OrderDataType data;
    @XmlElement(name = "Remarks")
    protected RemarksType remarks;
    @XmlElement(name = "Amendments")
    protected AmendmentsType amendments;
    @XmlElement(name = "LifecycleEvents")
    protected OrderLifecycleEvents lifecycleEvents;

    /**
     * Gets the value of the orderSummary property.
     * 
     * @return
     *     possible object is
     *     {@link OrderSummaryType }
     *     
     */
    public OrderSummaryType getOrderSummary() {
        return orderSummary;
    }

    /**
     * Sets the value of the orderSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderSummaryType }
     *     
     */
    public void setOrderSummary(OrderSummaryType value) {
        this.orderSummary = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDataType }
     *     
     */
    public OrderDataType getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDataType }
     *     
     */
    public void setData(OrderDataType value) {
        this.data = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link RemarksType }
     *     
     */
    public RemarksType getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemarksType }
     *     
     */
    public void setRemarks(RemarksType value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the amendments property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentsType }
     *     
     */
    public AmendmentsType getAmendments() {
        return amendments;
    }

    /**
     * Sets the value of the amendments property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentsType }
     *     
     */
    public void setAmendments(AmendmentsType value) {
        this.amendments = value;
    }

    /**
     * Gets the value of the lifecycleEvents property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLifecycleEvents }
     *     
     */
    public OrderLifecycleEvents getLifecycleEvents() {
        return lifecycleEvents;
    }

    /**
     * Sets the value of the lifecycleEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLifecycleEvents }
     *     
     */
    public void setLifecycleEvents(OrderLifecycleEvents value) {
        this.lifecycleEvents = value;
    }


    @Override
    public String toString() {
        return "GetOrderResponseType{" +
                "orderSummary=" + orderSummary +
                ", data=" + data +
                ", remarks=" + remarks +
                ", amendments=" + amendments +
                ", lifecycleEvents=" + lifecycleEvents +
                '}';
    }
}
