//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for GetOrderRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetOrderRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderId" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderIdType"/&gt;
 *         &lt;element name="View" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType" minOccurs="0"/&gt;
 *         &lt;element name="OrderDataFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderDataFilterType" minOccurs="0"/&gt;
 *         &lt;element name="RemarkFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}RemarkFilter" minOccurs="0"/&gt;
 *         &lt;element name="AmendmentFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}AmendmentFilterType" minOccurs="0"/&gt;
 *         &lt;element name="LifecycleEventFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderLifecycleEventFilterType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetOrderRequestType", propOrder = {
    "orderId",
    "view",
    "orderDataFilter",
    "remarkFilter",
    "amendmentFilter",
    "lifecycleEventFilter"
})
@XmlRootElement(name = "GetOrder", namespace = "http://xmlns.oracle.com/communications/ordermanagement")
public class GetOrderRequestType {

    @XmlElement(name = "OrderId", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String orderId;
    @XmlElement(name = "View")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String view;
    @XmlElement(name = "OrderDataFilter")
    protected OrderDataFilterType orderDataFilter;
    @XmlElement(name = "RemarkFilter")
    protected RemarkFilter remarkFilter;
    @XmlElement(name = "AmendmentFilter")
    protected AmendmentFilterType amendmentFilter;
    @XmlElement(name = "LifecycleEventFilter")
    protected OrderLifecycleEventFilterType lifecycleEventFilter;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getView() {
        return view;
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setView(String value) {
        this.view = value;
    }

    /**
     * Gets the value of the orderDataFilter property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDataFilterType }
     *     
     */
    public OrderDataFilterType getOrderDataFilter() {
        return orderDataFilter;
    }

    /**
     * Sets the value of the orderDataFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDataFilterType }
     *     
     */
    public void setOrderDataFilter(OrderDataFilterType value) {
        this.orderDataFilter = value;
    }

    /**
     * Gets the value of the remarkFilter property.
     * 
     * @return
     *     possible object is
     *     {@link RemarkFilter }
     *     
     */
    public RemarkFilter getRemarkFilter() {
        return remarkFilter;
    }

    /**
     * Sets the value of the remarkFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemarkFilter }
     *     
     */
    public void setRemarkFilter(RemarkFilter value) {
        this.remarkFilter = value;
    }

    /**
     * Gets the value of the amendmentFilter property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentFilterType }
     *     
     */
    public AmendmentFilterType getAmendmentFilter() {
        return amendmentFilter;
    }

    /**
     * Sets the value of the amendmentFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentFilterType }
     *     
     */
    public void setAmendmentFilter(AmendmentFilterType value) {
        this.amendmentFilter = value;
    }

    /**
     * Gets the value of the lifecycleEventFilter property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLifecycleEventFilterType }
     *     
     */
    public OrderLifecycleEventFilterType getLifecycleEventFilter() {
        return lifecycleEventFilter;
    }

    /**
     * Sets the value of the lifecycleEventFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLifecycleEventFilterType }
     *     
     */
    public void setLifecycleEventFilter(OrderLifecycleEventFilterType value) {
        this.lifecycleEventFilter = value;
    }

}
