//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GracePeriodTransitionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GracePeriodTransitionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="immediate"/&gt;
 *     &lt;enumeration value="infinite"/&gt;
 *     &lt;enumeration value="default"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GracePeriodTransitionType")
@XmlEnum
public enum GracePeriodTransitionType {

    @XmlEnumValue("immediate")
    IMMEDIATE("immediate"),
    @XmlEnumValue("infinite")
    INFINITE("infinite"),
    @XmlEnumValue("default")
    DEFAULT("default");
    private final String value;

    GracePeriodTransitionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GracePeriodTransitionType fromValue(String v) {
        for (GracePeriodTransitionType c: GracePeriodTransitionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
