//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 *   This fault is raised when the specified
 *                 order definition    cannot be found. Generally this
 *                 fault occurs for one of    the following reasons: an
 *                 incorrect order type or source    is specified, an
 *                 incorrect cartridge namespace or    version is
 *                 specified, or the user does has not been    granted
 *                 access to the creation task for the specified    order definition.
 * 
 * <p>Java class for InvalidOrderSpecificationFaultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvalidOrderSpecificationFaultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xmlns.oracle.com/communications/ordermanagement}FaultType"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvalidOrderSpecificationFaultType")
public class InvalidOrderSpecificationFaultType
    extends FaultType
{


}
