//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the james.rest.JamesOSSTrack.util.osmws.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateOrderBySpecification_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "CreateOrderBySpecification");
    private final static QName _CreateOrderBySpecificationResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "CreateOrderBySpecificationResponse");
    private final static QName _GetOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "GetOrder");
    private final static QName _GetOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "GetOrderResponse");
    private final static QName _ResumeOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "ResumeOrder");
    private final static QName _ResumeOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "ResumeOrderResponse");
    private final static QName _OrderNotFoundFault_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "OrderNotFoundFault");
    private final static QName _NotAuthorizedFault_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "NotAuthorizedFault");
    private final static QName _InvalidFindOrderFault_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "InvalidFindOrderFault");
    private final static QName _OrderTransactionNotAllowedFault_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "OrderTransactionNotAllowedFault");
    private final static QName _InvalidOrderSpecificationFault_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "InvalidOrderSpecificationFault");
    private final static QName _SuspendOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "SuspendOrder");
    private final static QName _SuspendOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "SuspendOrderResponse");
    private final static QName _CancelOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "CancelOrder");
    private final static QName _CancelOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "CancelOrderResponse");
    private final static QName _UpdateOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "UpdateOrder");
    private final static QName _UpdateOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "UpdateOrderResponse");
    private final static QName _FailOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "FailOrder");
    private final static QName _FailOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "FailOrderResponse");
    private final static QName _RetryOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "RetryOrder");
    private final static QName _RetryOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "RetryOrderResponse");
    private final static QName _AbortOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "AbortOrder");
    private final static QName _AbortOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "AbortOrderResponse");
    private final static QName _ResolveFailure_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "ResolveFailure");
    private final static QName _ResolveFailureResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "ResolveFailureResponse");
    private final static QName _FindOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "FindOrder");
    private final static QName _FindOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "FindOrderResponse");
    private final static QName _InvalidViewFault_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "InvalidViewFault");
    private final static QName _InvalidOrderDataFilterFault_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "InvalidOrderDataFilterFault");
    private final static QName _InvalidOrderDataFault_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "InvalidOrderDataFault");
    private final static QName _CreateOrder_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "CreateOrder");
    private final static QName _CreateOrderResponse_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "CreateOrderResponse");
    private final static QName _ValidationResult_QNAME = new QName("http://xmlns.oracle.com/communications/ordermanagement", "ValidationResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: james.rest.JamesOSSTrack.util.osmws.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderStatesType }
     * 
     */
    public OrderStatesType createOrderStatesType() {
        return new OrderStatesType();
    }

    /**
     * Create an instance of {@link OrderDataDeltaType }
     * 
     */
    public OrderDataDeltaType createOrderDataDeltaType() {
        return new OrderDataDeltaType();
    }

    /**
     * Create an instance of {@link FindOrderRequestType }
     * 
     */
    public FindOrderRequestType createFindOrderRequestType() {
        return new FindOrderRequestType();
    }

    /**
     * Create an instance of {@link FindOrderRequestType.OrderBy }
     * 
     */
    public FindOrderRequestType.OrderBy createFindOrderRequestTypeOrderBy() {
        return new FindOrderRequestType.OrderBy();
    }

    /**
     * Create an instance of {@link FindOrderRequestType.OrderBy.OrderField }
     * 
     */
    public FindOrderRequestType.OrderBy.OrderField createFindOrderRequestTypeOrderByOrderField() {
        return new FindOrderRequestType.OrderBy.OrderField();
    }

    /**
     * Create an instance of {@link FindOrderRequestType.SelectBy }
     * 
     */
    public FindOrderRequestType.SelectBy createFindOrderRequestTypeSelectBy() {
        return new FindOrderRequestType.SelectBy();
    }

    /**
     * Create an instance of {@link FindOrderRequestType.SelectBy.Field }
     * 
     */
    public FindOrderRequestType.SelectBy.Field createFindOrderRequestTypeSelectByField() {
        return new FindOrderRequestType.SelectBy.Field();
    }

    /**
     * Create an instance of {@link UpdateOrderResponseType }
     * 
     */
    public UpdateOrderResponseType createUpdateOrderResponseType() {
        return new UpdateOrderResponseType();
    }

    /**
     * Create an instance of {@link CreateOrderBySpecificationRequestType }
     * 
     */
    public CreateOrderBySpecificationRequestType createCreateOrderBySpecificationRequestType() {
        return new CreateOrderBySpecificationRequestType();
    }

    /**
     * Create an instance of {@link CreateOrderBySpecificationResponseType }
     * 
     */
    public CreateOrderBySpecificationResponseType createCreateOrderBySpecificationResponseType() {
        return new CreateOrderBySpecificationResponseType();
    }

    /**
     * Create an instance of {@link GetOrderRequestType }
     * 
     */
    public GetOrderRequestType createGetOrderRequestType() {
        return new GetOrderRequestType();
    }

    /**
     * Create an instance of {@link GetOrderResponseType }
     * 
     */
    public GetOrderResponseType createGetOrderResponseType() {
        return new GetOrderResponseType();
    }

    /**
     * Create an instance of {@link ResumeOrderRequestType }
     * 
     */
    public ResumeOrderRequestType createResumeOrderRequestType() {
        return new ResumeOrderRequestType();
    }

    /**
     * Create an instance of {@link ResumeOrderResponseType }
     * 
     */
    public ResumeOrderResponseType createResumeOrderResponseType() {
        return new ResumeOrderResponseType();
    }

    /**
     * Create an instance of {@link OrderNotFoundFaultType }
     * 
     */
    public OrderNotFoundFaultType createOrderNotFoundFaultType() {
        return new OrderNotFoundFaultType();
    }

    /**
     * Create an instance of {@link NotAuthorizedFaultType }
     * 
     */
    public NotAuthorizedFaultType createNotAuthorizedFaultType() {
        return new NotAuthorizedFaultType();
    }

    /**
     * Create an instance of {@link InvalidFindOrderFaultType }
     * 
     */
    public InvalidFindOrderFaultType createInvalidFindOrderFaultType() {
        return new InvalidFindOrderFaultType();
    }

    /**
     * Create an instance of {@link OrderTransactionNotAllowedFaultType }
     * 
     */
    public OrderTransactionNotAllowedFaultType createOrderTransactionNotAllowedFaultType() {
        return new OrderTransactionNotAllowedFaultType();
    }

    /**
     * Create an instance of {@link InvalidOrderSpecificationFaultType }
     * 
     */
    public InvalidOrderSpecificationFaultType createInvalidOrderSpecificationFaultType() {
        return new InvalidOrderSpecificationFaultType();
    }

    /**
     * Create an instance of {@link SuspendOrderRequestType }
     * 
     */
    public SuspendOrderRequestType createSuspendOrderRequestType() {
        return new SuspendOrderRequestType();
    }

    /**
     * Create an instance of {@link SuspendOrderResponseType }
     * 
     */
    public SuspendOrderResponseType createSuspendOrderResponseType() {
        return new SuspendOrderResponseType();
    }

    /**
     * Create an instance of {@link CancelOrderRequestType }
     * 
     */
    public CancelOrderRequestType createCancelOrderRequestType() {
        return new CancelOrderRequestType();
    }

    /**
     * Create an instance of {@link CancelOrderResponseType }
     * 
     */
    public CancelOrderResponseType createCancelOrderResponseType() {
        return new CancelOrderResponseType();
    }

    /**
     * Create an instance of {@link UpdateOrderRequestType }
     * 
     */
    public UpdateOrderRequestType createUpdateOrderRequestType() {
        return new UpdateOrderRequestType();
    }

    /**
     * Create an instance of {@link FailOrderRequestType }
     * 
     */
    public FailOrderRequestType createFailOrderRequestType() {
        return new FailOrderRequestType();
    }

    /**
     * Create an instance of {@link FailOrderResponseType }
     * 
     */
    public FailOrderResponseType createFailOrderResponseType() {
        return new FailOrderResponseType();
    }

    /**
     * Create an instance of {@link RetryOrderRequestType }
     * 
     */
    public RetryOrderRequestType createRetryOrderRequestType() {
        return new RetryOrderRequestType();
    }

    /**
     * Create an instance of {@link RetryOrderResponseType }
     * 
     */
    public RetryOrderResponseType createRetryOrderResponseType() {
        return new RetryOrderResponseType();
    }

    /**
     * Create an instance of {@link AbortOrderRequestType }
     * 
     */
    public AbortOrderRequestType createAbortOrderRequestType() {
        return new AbortOrderRequestType();
    }

    /**
     * Create an instance of {@link AbortOrderResponseType }
     * 
     */
    public AbortOrderResponseType createAbortOrderResponseType() {
        return new AbortOrderResponseType();
    }

    /**
     * Create an instance of {@link ResolveFailureRequestType }
     * 
     */
    public ResolveFailureRequestType createResolveFailureRequestType() {
        return new ResolveFailureRequestType();
    }

    /**
     * Create an instance of {@link ResolveFailureResponseType }
     * 
     */
    public ResolveFailureResponseType createResolveFailureResponseType() {
        return new ResolveFailureResponseType();
    }

    /**
     * Create an instance of {@link FindOrderResponseType }
     * 
     */
    public FindOrderResponseType createFindOrderResponseType() {
        return new FindOrderResponseType();
    }

    /**
     * Create an instance of {@link GetOrderFault }
     * 
     */
    public GetOrderFault createGetOrderFault() {
        return new GetOrderFault();
    }

    /**
     * Create an instance of {@link InvalidViewFaultType }
     * 
     */
    public InvalidViewFaultType createInvalidViewFaultType() {
        return new InvalidViewFaultType();
    }

    /**
     * Create an instance of {@link InvalidOrderDataFilterFaultType }
     * 
     */
    public InvalidOrderDataFilterFaultType createInvalidOrderDataFilterFaultType() {
        return new InvalidOrderDataFilterFaultType();
    }

    /**
     * Create an instance of {@link InvalidOrderDataFaultType }
     * 
     */
    public InvalidOrderDataFaultType createInvalidOrderDataFaultType() {
        return new InvalidOrderDataFaultType();
    }

    /**
     * Create an instance of {@link CreateOrderRequestType }
     * 
     */
    public CreateOrderRequestType createCreateOrderRequestType() {
        return new CreateOrderRequestType();
    }

    /**
     * Create an instance of {@link CreateOrderResponseType }
     * 
     */
    public CreateOrderResponseType createCreateOrderResponseType() {
        return new CreateOrderResponseType();
    }

    /**
     * Create an instance of {@link ValidationType }
     * 
     */
    public ValidationType createValidationType() {
        return new ValidationType();
    }

    /**
     * Create an instance of {@link DateRangeType }
     * 
     */
    public DateRangeType createDateRangeType() {
        return new DateRangeType();
    }

    /**
     * Create an instance of {@link OrderSummaryType }
     * 
     */
    public OrderSummaryType createOrderSummaryType() {
        return new OrderSummaryType();
    }

    /**
     * Create an instance of {@link OrderSpecificationType }
     * 
     */
    public OrderSpecificationType createOrderSpecificationType() {
        return new OrderSpecificationType();
    }

    /**
     * Create an instance of {@link CartridgeType }
     * 
     */
    public CartridgeType createCartridgeType() {
        return new CartridgeType();
    }

    /**
     * Create an instance of {@link OrderDetailType }
     * 
     */
    public OrderDetailType createOrderDetailType() {
        return new OrderDetailType();
    }

    /**
     * Create an instance of {@link OrderDataType }
     * 
     */
    public OrderDataType createOrderDataType() {
        return new OrderDataType();
    }

    /**
     * Create an instance of {@link RemarkType }
     * 
     */
    public RemarkType createRemarkType() {
        return new RemarkType();
    }

    /**
     * Create an instance of {@link AttachmentType }
     * 
     */
    public AttachmentType createAttachmentType() {
        return new AttachmentType();
    }

    /**
     * Create an instance of {@link DataChangeRequestType }
     * 
     */
    public DataChangeRequestType createDataChangeRequestType() {
        return new DataChangeRequestType();
    }

    /**
     * Create an instance of {@link CreateRemarkType }
     * 
     */
    public CreateRemarkType createCreateRemarkType() {
        return new CreateRemarkType();
    }

    /**
     * Create an instance of {@link FaultType }
     * 
     */
    public FaultType createFaultType() {
        return new FaultType();
    }

    /**
     * Create an instance of {@link AmendmentSummaryType }
     * 
     */
    public AmendmentSummaryType createAmendmentSummaryType() {
        return new AmendmentSummaryType();
    }

    /**
     * Create an instance of {@link AttachmentFilter }
     * 
     */
    public AttachmentFilter createAttachmentFilter() {
        return new AttachmentFilter();
    }

    /**
     * Create an instance of {@link RemarkFilter }
     * 
     */
    public RemarkFilter createRemarkFilter() {
        return new RemarkFilter();
    }

    /**
     * Create an instance of {@link OrderDataFilterType }
     * 
     */
    public OrderDataFilterType createOrderDataFilterType() {
        return new OrderDataFilterType();
    }

    /**
     * Create an instance of {@link RemarksType }
     * 
     */
    public RemarksType createRemarksType() {
        return new RemarksType();
    }

    /**
     * Create an instance of {@link RemarkResponseType }
     * 
     */
    public RemarkResponseType createRemarkResponseType() {
        return new RemarkResponseType();
    }

    /**
     * Create an instance of {@link AttachmentResponseType }
     * 
     */
    public AttachmentResponseType createAttachmentResponseType() {
        return new AttachmentResponseType();
    }

    /**
     * Create an instance of {@link OrderKeyType }
     * 
     */
    public OrderKeyType createOrderKeyType() {
        return new OrderKeyType();
    }

    /**
     * Create an instance of {@link DurationRangeType }
     * 
     */
    public DurationRangeType createDurationRangeType() {
        return new DurationRangeType();
    }

    /**
     * Create an instance of {@link AmendmentsType }
     * 
     */
    public AmendmentsType createAmendmentsType() {
        return new AmendmentsType();
    }

    /**
     * Create an instance of {@link AmendmentDetailType }
     * 
     */
    public AmendmentDetailType createAmendmentDetailType() {
        return new AmendmentDetailType();
    }

    /**
     * Create an instance of {@link AmendmentFilterType }
     * 
     */
    public AmendmentFilterType createAmendmentFilterType() {
        return new AmendmentFilterType();
    }

    /**
     * Create an instance of {@link OrderLifecycleEventFilterType }
     * 
     */
    public OrderLifecycleEventFilterType createOrderLifecycleEventFilterType() {
        return new OrderLifecycleEventFilterType();
    }

    /**
     * Create an instance of {@link OrderLifecycleEvents }
     * 
     */
    public OrderLifecycleEvents createOrderLifecycleEvents() {
        return new OrderLifecycleEvents();
    }

    /**
     * Create an instance of {@link OrderLifecycleEventType }
     * 
     */
    public OrderLifecycleEventType createOrderLifecycleEventType() {
        return new OrderLifecycleEventType();
    }

    /**
     * Create an instance of {@link ValidationMessageType }
     * 
     */
    public ValidationMessageType createValidationMessageType() {
        return new ValidationMessageType();
    }

    /**
     * Create an instance of {@link ValidationMessageLocationType }
     * 
     */
    public ValidationMessageLocationType createValidationMessageLocationType() {
        return new ValidationMessageLocationType();
    }

    /**
     * Create an instance of {@link OrderComponentReferenceType }
     * 
     */
    public OrderComponentReferenceType createOrderComponentReferenceType() {
        return new OrderComponentReferenceType();
    }

    /**
     * Create an instance of {@link OrderStatesType.OrderState }
     * 
     */
    public OrderStatesType.OrderState createOrderStatesTypeOrderState() {
        return new OrderStatesType.OrderState();
    }

    /**
     * Create an instance of {@link OrderDataDeltaType.Add }
     * 
     */
    public OrderDataDeltaType.Add createOrderDataDeltaTypeAdd() {
        return new OrderDataDeltaType.Add();
    }

    /**
     * Create an instance of {@link OrderDataDeltaType.Update }
     * 
     */
    public OrderDataDeltaType.Update createOrderDataDeltaTypeUpdate() {
        return new OrderDataDeltaType.Update();
    }

    /**
     * Create an instance of {@link OrderDataDeltaType.Delete }
     * 
     */
    public OrderDataDeltaType.Delete createOrderDataDeltaTypeDelete() {
        return new OrderDataDeltaType.Delete();
    }

    /**
     * Create an instance of {@link FindOrderRequestType.ViewBy }
     * 
     */
    public FindOrderRequestType.ViewBy createFindOrderRequestTypeViewBy() {
        return new FindOrderRequestType.ViewBy();
    }

    /**
     * Create an instance of {@link FindOrderRequestType.OrderBy.OrderField.Field }
     * 
     */
    public FindOrderRequestType.OrderBy.OrderField.Field createFindOrderRequestTypeOrderByOrderFieldField() {
        return new FindOrderRequestType.OrderBy.OrderField.Field();
    }

    /**
     * Create an instance of {@link FindOrderRequestType.SelectBy.Field.InList }
     * 
     */
    public FindOrderRequestType.SelectBy.Field.InList createFindOrderRequestTypeSelectByFieldInList() {
        return new FindOrderRequestType.SelectBy.Field.InList();
    }

    /**
     * Create an instance of {@link UpdateOrderResponseType.OrderAlreadyStartedWarning }
     * 
     */
    public UpdateOrderResponseType.OrderAlreadyStartedWarning createUpdateOrderResponseTypeOrderAlreadyStartedWarning() {
        return new UpdateOrderResponseType.OrderAlreadyStartedWarning();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrderBySpecificationRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateOrderBySpecificationRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "CreateOrderBySpecification")
    public JAXBElement<CreateOrderBySpecificationRequestType> createCreateOrderBySpecification(CreateOrderBySpecificationRequestType value) {
        return new JAXBElement<CreateOrderBySpecificationRequestType>(_CreateOrderBySpecification_QNAME, CreateOrderBySpecificationRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrderBySpecificationResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateOrderBySpecificationResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "CreateOrderBySpecificationResponse")
    public JAXBElement<CreateOrderBySpecificationResponseType> createCreateOrderBySpecificationResponse(CreateOrderBySpecificationResponseType value) {
        return new JAXBElement<CreateOrderBySpecificationResponseType>(_CreateOrderBySpecificationResponse_QNAME, CreateOrderBySpecificationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "GetOrder")
    public JAXBElement<GetOrderRequestType> createGetOrder(GetOrderRequestType value) {
        return new JAXBElement<GetOrderRequestType>(_GetOrder_QNAME, GetOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "GetOrderResponse")
    public JAXBElement<GetOrderResponseType> createGetOrderResponse(GetOrderResponseType value) {
        return new JAXBElement<GetOrderResponseType>(_GetOrderResponse_QNAME, GetOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResumeOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResumeOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "ResumeOrder")
    public JAXBElement<ResumeOrderRequestType> createResumeOrder(ResumeOrderRequestType value) {
        return new JAXBElement<ResumeOrderRequestType>(_ResumeOrder_QNAME, ResumeOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResumeOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResumeOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "ResumeOrderResponse")
    public JAXBElement<ResumeOrderResponseType> createResumeOrderResponse(ResumeOrderResponseType value) {
        return new JAXBElement<ResumeOrderResponseType>(_ResumeOrderResponse_QNAME, ResumeOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderNotFoundFaultType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OrderNotFoundFaultType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "OrderNotFoundFault")
    public JAXBElement<OrderNotFoundFaultType> createOrderNotFoundFault(OrderNotFoundFaultType value) {
        return new JAXBElement<OrderNotFoundFaultType>(_OrderNotFoundFault_QNAME, OrderNotFoundFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotAuthorizedFaultType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NotAuthorizedFaultType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "NotAuthorizedFault")
    public JAXBElement<NotAuthorizedFaultType> createNotAuthorizedFault(NotAuthorizedFaultType value) {
        return new JAXBElement<NotAuthorizedFaultType>(_NotAuthorizedFault_QNAME, NotAuthorizedFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidFindOrderFaultType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvalidFindOrderFaultType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "InvalidFindOrderFault")
    public JAXBElement<InvalidFindOrderFaultType> createInvalidFindOrderFault(InvalidFindOrderFaultType value) {
        return new JAXBElement<InvalidFindOrderFaultType>(_InvalidFindOrderFault_QNAME, InvalidFindOrderFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderTransactionNotAllowedFaultType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OrderTransactionNotAllowedFaultType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "OrderTransactionNotAllowedFault")
    public JAXBElement<OrderTransactionNotAllowedFaultType> createOrderTransactionNotAllowedFault(OrderTransactionNotAllowedFaultType value) {
        return new JAXBElement<OrderTransactionNotAllowedFaultType>(_OrderTransactionNotAllowedFault_QNAME, OrderTransactionNotAllowedFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidOrderSpecificationFaultType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvalidOrderSpecificationFaultType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "InvalidOrderSpecificationFault")
    public JAXBElement<InvalidOrderSpecificationFaultType> createInvalidOrderSpecificationFault(InvalidOrderSpecificationFaultType value) {
        return new JAXBElement<InvalidOrderSpecificationFaultType>(_InvalidOrderSpecificationFault_QNAME, InvalidOrderSpecificationFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SuspendOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SuspendOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "SuspendOrder")
    public JAXBElement<SuspendOrderRequestType> createSuspendOrder(SuspendOrderRequestType value) {
        return new JAXBElement<SuspendOrderRequestType>(_SuspendOrder_QNAME, SuspendOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SuspendOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SuspendOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "SuspendOrderResponse")
    public JAXBElement<SuspendOrderResponseType> createSuspendOrderResponse(SuspendOrderResponseType value) {
        return new JAXBElement<SuspendOrderResponseType>(_SuspendOrderResponse_QNAME, SuspendOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "CancelOrder")
    public JAXBElement<CancelOrderRequestType> createCancelOrder(CancelOrderRequestType value) {
        return new JAXBElement<CancelOrderRequestType>(_CancelOrder_QNAME, CancelOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "CancelOrderResponse")
    public JAXBElement<CancelOrderResponseType> createCancelOrderResponse(CancelOrderResponseType value) {
        return new JAXBElement<CancelOrderResponseType>(_CancelOrderResponse_QNAME, CancelOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "UpdateOrder")
    public JAXBElement<UpdateOrderRequestType> createUpdateOrder(UpdateOrderRequestType value) {
        return new JAXBElement<UpdateOrderRequestType>(_UpdateOrder_QNAME, UpdateOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "UpdateOrderResponse")
    public JAXBElement<UpdateOrderResponseType> createUpdateOrderResponse(UpdateOrderResponseType value) {
        return new JAXBElement<UpdateOrderResponseType>(_UpdateOrderResponse_QNAME, UpdateOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FailOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FailOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "FailOrder")
    public JAXBElement<FailOrderRequestType> createFailOrder(FailOrderRequestType value) {
        return new JAXBElement<FailOrderRequestType>(_FailOrder_QNAME, FailOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FailOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FailOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "FailOrderResponse")
    public JAXBElement<FailOrderResponseType> createFailOrderResponse(FailOrderResponseType value) {
        return new JAXBElement<FailOrderResponseType>(_FailOrderResponse_QNAME, FailOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetryOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetryOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "RetryOrder")
    public JAXBElement<RetryOrderRequestType> createRetryOrder(RetryOrderRequestType value) {
        return new JAXBElement<RetryOrderRequestType>(_RetryOrder_QNAME, RetryOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetryOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetryOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "RetryOrderResponse")
    public JAXBElement<RetryOrderResponseType> createRetryOrderResponse(RetryOrderResponseType value) {
        return new JAXBElement<RetryOrderResponseType>(_RetryOrderResponse_QNAME, RetryOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbortOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbortOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "AbortOrder")
    public JAXBElement<AbortOrderRequestType> createAbortOrder(AbortOrderRequestType value) {
        return new JAXBElement<AbortOrderRequestType>(_AbortOrder_QNAME, AbortOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbortOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbortOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "AbortOrderResponse")
    public JAXBElement<AbortOrderResponseType> createAbortOrderResponse(AbortOrderResponseType value) {
        return new JAXBElement<AbortOrderResponseType>(_AbortOrderResponse_QNAME, AbortOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResolveFailureRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResolveFailureRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "ResolveFailure")
    public JAXBElement<ResolveFailureRequestType> createResolveFailure(ResolveFailureRequestType value) {
        return new JAXBElement<ResolveFailureRequestType>(_ResolveFailure_QNAME, ResolveFailureRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResolveFailureResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResolveFailureResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "ResolveFailureResponse")
    public JAXBElement<ResolveFailureResponseType> createResolveFailureResponse(ResolveFailureResponseType value) {
        return new JAXBElement<ResolveFailureResponseType>(_ResolveFailureResponse_QNAME, ResolveFailureResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FindOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "FindOrder")
    public JAXBElement<FindOrderRequestType> createFindOrder(FindOrderRequestType value) {
        return new JAXBElement<FindOrderRequestType>(_FindOrder_QNAME, FindOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FindOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "FindOrderResponse")
    public JAXBElement<FindOrderResponseType> createFindOrderResponse(FindOrderResponseType value) {
        return new JAXBElement<FindOrderResponseType>(_FindOrderResponse_QNAME, FindOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidViewFaultType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvalidViewFaultType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "InvalidViewFault")
    public JAXBElement<InvalidViewFaultType> createInvalidViewFault(InvalidViewFaultType value) {
        return new JAXBElement<InvalidViewFaultType>(_InvalidViewFault_QNAME, InvalidViewFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidOrderDataFilterFaultType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvalidOrderDataFilterFaultType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "InvalidOrderDataFilterFault")
    public JAXBElement<InvalidOrderDataFilterFaultType> createInvalidOrderDataFilterFault(InvalidOrderDataFilterFaultType value) {
        return new JAXBElement<InvalidOrderDataFilterFaultType>(_InvalidOrderDataFilterFault_QNAME, InvalidOrderDataFilterFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidOrderDataFaultType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvalidOrderDataFaultType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "InvalidOrderDataFault")
    public JAXBElement<InvalidOrderDataFaultType> createInvalidOrderDataFault(InvalidOrderDataFaultType value) {
        return new JAXBElement<InvalidOrderDataFaultType>(_InvalidOrderDataFault_QNAME, InvalidOrderDataFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrderRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateOrderRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "CreateOrder")
    public JAXBElement<CreateOrderRequestType> createCreateOrder(CreateOrderRequestType value) {
        return new JAXBElement<CreateOrderRequestType>(_CreateOrder_QNAME, CreateOrderRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrderResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateOrderResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "CreateOrderResponse")
    public JAXBElement<CreateOrderResponseType> createCreateOrderResponse(CreateOrderResponseType value) {
        return new JAXBElement<CreateOrderResponseType>(_CreateOrderResponse_QNAME, CreateOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/ordermanagement", name = "ValidationResult")
    public JAXBElement<ValidationType> createValidationResult(ValidationType value) {
        return new JAXBElement<ValidationType>(_ValidationResult_QNAME, ValidationType.class, null, value);
    }

}
