//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *     This fault is raised when the
 *                 transaction being    attempted is not permitted. This
 *                 fault generally occurs    for two reasons: the
 *                 requesting user is not authorized    to perform the
 *                 transaction, or the order lifecycle policy    associated
 *                 with the order does not permit the requested
 *                 transaction from being performed at this time.
 * 
 * <p>Java class for OrderTransactionNotAllowedFaultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderTransactionNotAllowedFaultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xmlns.oracle.com/communications/ordermanagement}FaultType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderId" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityIdType"/&gt;
 *         &lt;element name="Policy" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType"/&gt;
 *         &lt;element name="OrderState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType"/&gt;
 *         &lt;element name="Cartridge" type="{http://xmlns.oracle.com/communications/ordermanagement}CartridgeType"/&gt;
 *         &lt;element name="Transaction" type="{http://xmlns.oracle.com/communications/ordermanagement}TransactionType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderTransactionNotAllowedFaultType", propOrder = {
    "orderId",
    "policy",
    "orderState",
    "cartridge",
    "transaction"
})
public class OrderTransactionNotAllowedFaultType
    extends FaultType
{

    @XmlElement(name = "OrderId")
    protected long orderId;
    @XmlElement(name = "Policy", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String policy;
    @XmlElement(name = "OrderState", required = true)
    @XmlSchemaType(name = "string")
    protected OrderStateType orderState;
    @XmlElement(name = "Cartridge", required = true)
    protected CartridgeType cartridge;
    @XmlElement(name = "Transaction", required = true)
    @XmlSchemaType(name = "string")
    protected TransactionType transaction;

    /**
     * Gets the value of the orderId property.
     * 
     */
    public long getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     */
    public void setOrderId(long value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the policy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicy() {
        return policy;
    }

    /**
     * Sets the value of the policy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicy(String value) {
        this.policy = value;
    }

    /**
     * Gets the value of the orderState property.
     * 
     * @return
     *     possible object is
     *     {@link OrderStateType }
     *     
     */
    public OrderStateType getOrderState() {
        return orderState;
    }

    /**
     * Sets the value of the orderState property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderStateType }
     *     
     */
    public void setOrderState(OrderStateType value) {
        this.orderState = value;
    }

    /**
     * Gets the value of the cartridge property.
     * 
     * @return
     *     possible object is
     *     {@link CartridgeType }
     *     
     */
    public CartridgeType getCartridge() {
        return cartridge;
    }

    /**
     * Sets the value of the cartridge property.
     * 
     * @param value
     *     allowed object is
     *     {@link CartridgeType }
     *     
     */
    public void setCartridge(CartridgeType value) {
        this.cartridge = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionType }
     *     
     */
    public TransactionType getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionType }
     *     
     */
    public void setTransaction(TransactionType value) {
        this.transaction = value;
    }

}
