//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *     Common base type for operations that
 *                 perform a state    transition on the order where a grace
 *                 period is allowed.
 * 
 * <p>Java class for OrderStateTransitionRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderStateTransitionRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderId" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderIdType"/&gt;
 *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="GracePeriodExpiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *           &lt;element name="GracePeriodExpiry" type="{http://xmlns.oracle.com/communications/ordermanagement}GracePeriodTransitionType" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="EventInterval" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderStateTransitionRequestType", propOrder = {
    "orderId",
    "reason",
    "gracePeriodExpiryDate",
    "gracePeriodExpiry",
    "eventInterval"
})
@XmlSeeAlso({
    SuspendOrderRequestType.class,
    CancelOrderRequestType.class,
    FailOrderRequestType.class
})
public abstract class OrderStateTransitionRequestType {

    @XmlElement(name = "OrderId", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String orderId;
    @XmlElement(name = "Reason")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String reason;
    @XmlElement(name = "GracePeriodExpiryDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gracePeriodExpiryDate;
    @XmlElement(name = "GracePeriodExpiry")
    @XmlSchemaType(name = "string")
    protected GracePeriodTransitionType gracePeriodExpiry;
    @XmlElement(name = "EventInterval")
    protected Duration eventInterval;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the gracePeriodExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGracePeriodExpiryDate() {
        return gracePeriodExpiryDate;
    }

    /**
     * Sets the value of the gracePeriodExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGracePeriodExpiryDate(XMLGregorianCalendar value) {
        this.gracePeriodExpiryDate = value;
    }

    /**
     * Gets the value of the gracePeriodExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link GracePeriodTransitionType }
     *     
     */
    public GracePeriodTransitionType getGracePeriodExpiry() {
        return gracePeriodExpiry;
    }

    /**
     * Sets the value of the gracePeriodExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link GracePeriodTransitionType }
     *     
     */
    public void setGracePeriodExpiry(GracePeriodTransitionType value) {
        this.gracePeriodExpiry = value;
    }

    /**
     * Gets the value of the eventInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getEventInterval() {
        return eventInterval;
    }

    /**
     * Sets the value of the eventInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setEventInterval(Duration value) {
        this.eventInterval = value;
    }

}
