//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OrderStatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderStatesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderState" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="OrderState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType"/&gt;
 *                   &lt;element name="TransitionStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="TransitionCompletedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                   &lt;element name="ActualDuration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/&gt;
 *                   &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *                   &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderStatesType", propOrder = {
    "orderState"
})
public class OrderStatesType {

    @XmlElement(name = "OrderState")
    protected List<OrderState> orderState;

    /**
     * Gets the value of the orderState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderState }
     * 
     * 
     */
    public List<OrderState> getOrderState() {
        if (orderState == null) {
            orderState = new ArrayList<OrderState>();
        }
        return this.orderState;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="OrderState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType"/&gt;
     *         &lt;element name="TransitionStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="TransitionCompletedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *         &lt;element name="ActualDuration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/&gt;
     *         &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
     *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderState",
        "transitionStartDate",
        "transitionCompletedDate",
        "actualDuration",
        "user",
        "reason"
    })
    public static class OrderState {

        @XmlElement(name = "OrderState", required = true)
        @XmlSchemaType(name = "string")
        protected OrderStateType orderState;
        @XmlElement(name = "TransitionStartDate", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar transitionStartDate;
        @XmlElement(name = "TransitionCompletedDate")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar transitionCompletedDate;
        @XmlElement(name = "ActualDuration")
        protected Duration actualDuration;
        @XmlElement(name = "User", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String user;
        @XmlElement(name = "Reason")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String reason;

        /**
         * Gets the value of the orderState property.
         * 
         * @return
         *     possible object is
         *     {@link OrderStateType }
         *     
         */
        public OrderStateType getOrderState() {
            return orderState;
        }

        /**
         * Sets the value of the orderState property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderStateType }
         *     
         */
        public void setOrderState(OrderStateType value) {
            this.orderState = value;
        }

        /**
         * Gets the value of the transitionStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTransitionStartDate() {
            return transitionStartDate;
        }

        /**
         * Sets the value of the transitionStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTransitionStartDate(XMLGregorianCalendar value) {
            this.transitionStartDate = value;
        }

        /**
         * Gets the value of the transitionCompletedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTransitionCompletedDate() {
            return transitionCompletedDate;
        }

        /**
         * Sets the value of the transitionCompletedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTransitionCompletedDate(XMLGregorianCalendar value) {
            this.transitionCompletedDate = value;
        }

        /**
         * Gets the value of the actualDuration property.
         * 
         * @return
         *     possible object is
         *     {@link Duration }
         *     
         */
        public Duration getActualDuration() {
            return actualDuration;
        }

        /**
         * Sets the value of the actualDuration property.
         * 
         * @param value
         *     allowed object is
         *     {@link Duration }
         *     
         */
        public void setActualDuration(Duration value) {
            this.actualDuration = value;
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUser() {
            return user;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUser(String value) {
            this.user = value;
        }

        /**
         * Gets the value of the reason property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReason() {
            return reason;
        }

        /**
         * Sets the value of the reason property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReason(String value) {
            this.reason = value;
        }

    }

}
