//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *     This type provides summary
 *                 information about an order.
 * 
 * <p>Java class for OrderSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderSummaryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderIdType"/&gt;
 *         &lt;element name="Key" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderKeyType" minOccurs="0"/&gt;
 *         &lt;element name="Specification" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderSpecificationType"/&gt;
 *         &lt;element name="State" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType"/&gt;
 *         &lt;element name="TargetState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType" minOccurs="0"/&gt;
 *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreatedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="RequestedDeliveryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ExpectedStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ExpectedDuration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/&gt;
 *         &lt;element name="ExpectedOrderCompletionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ViewName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProcessStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Priority" type="{http://xmlns.oracle.com/communications/ordermanagement}PriorityType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderSummaryType", propOrder = {
    "id",
    "key",
    "specification",
    "state",
    "targetState",
    "reference",
    "createdDate",
    "requestedDeliveryDate",
    "expectedStartDate",
    "expectedDuration",
    "expectedOrderCompletionDate",
    "viewName",
    "processStatus",
    "priority"
})
public class OrderSummaryType {

    @XmlElement(name = "Id", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String id;
    @XmlElement(name = "Key")
    protected OrderKeyType key;
    @XmlElement(name = "Specification", required = true)
    protected OrderSpecificationType specification;
    @XmlElement(name = "State", required = true)
    @XmlSchemaType(name = "string")
    protected OrderStateType state;
    @XmlElement(name = "TargetState")
    @XmlSchemaType(name = "string")
    protected OrderStateType targetState;
    @XmlElement(name = "Reference")
    protected String reference;
    @XmlElement(name = "CreatedDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDate;
    @XmlElement(name = "RequestedDeliveryDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestedDeliveryDate;
    @XmlElement(name = "ExpectedStartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expectedStartDate;
    @XmlElement(name = "ExpectedDuration")
    protected Duration expectedDuration;
    @XmlElement(name = "ExpectedOrderCompletionDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expectedOrderCompletionDate;
    @XmlElement(name = "ViewName")
    protected String viewName;
    @XmlElement(name = "ProcessStatus")
    protected String processStatus;
    @XmlElement(name = "Priority")
    protected int priority;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link OrderKeyType }
     *     
     */
    public OrderKeyType getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderKeyType }
     *     
     */
    public void setKey(OrderKeyType value) {
        this.key = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link OrderSpecificationType }
     *     
     */
    public OrderSpecificationType getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderSpecificationType }
     *     
     */
    public void setSpecification(OrderSpecificationType value) {
        this.specification = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link OrderStateType }
     *     
     */
    public OrderStateType getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderStateType }
     *     
     */
    public void setState(OrderStateType value) {
        this.state = value;
    }

    /**
     * Gets the value of the targetState property.
     * 
     * @return
     *     possible object is
     *     {@link OrderStateType }
     *     
     */
    public OrderStateType getTargetState() {
        return targetState;
    }

    /**
     * Sets the value of the targetState property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderStateType }
     *     
     */
    public void setTargetState(OrderStateType value) {
        this.targetState = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the createdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDate(XMLGregorianCalendar value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the requestedDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestedDeliveryDate() {
        return requestedDeliveryDate;
    }

    /**
     * Sets the value of the requestedDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestedDeliveryDate(XMLGregorianCalendar value) {
        this.requestedDeliveryDate = value;
    }

    /**
     * Gets the value of the expectedStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpectedStartDate() {
        return expectedStartDate;
    }

    /**
     * Sets the value of the expectedStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpectedStartDate(XMLGregorianCalendar value) {
        this.expectedStartDate = value;
    }

    /**
     * Gets the value of the expectedDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getExpectedDuration() {
        return expectedDuration;
    }

    /**
     * Sets the value of the expectedDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setExpectedDuration(Duration value) {
        this.expectedDuration = value;
    }

    /**
     * Gets the value of the expectedOrderCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpectedOrderCompletionDate() {
        return expectedOrderCompletionDate;
    }

    /**
     * Sets the value of the expectedOrderCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpectedOrderCompletionDate(XMLGregorianCalendar value) {
        this.expectedOrderCompletionDate = value;
    }

    /**
     * Gets the value of the viewName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewName() {
        return viewName;
    }

    /**
     * Sets the value of the viewName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewName(String value) {
        this.viewName = value;
    }

    /**
     * Gets the value of the processStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * Sets the value of the processStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessStatus(String value) {
        this.processStatus = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

}
