//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RemarkResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemarkResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RemarkId" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityIdType"/&gt;
 *         &lt;element name="Attachment" type="{http://xmlns.oracle.com/communications/ordermanagement}AttachmentResponseType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemarkResponseType", propOrder = {
    "remarkId",
    "attachment"
})
public class RemarkResponseType {

    @XmlElement(name = "RemarkId")
    protected long remarkId;
    @XmlElement(name = "Attachment")
    protected List<AttachmentResponseType> attachment;

    /**
     * Gets the value of the remarkId property.
     * 
     */
    public long getRemarkId() {
        return remarkId;
    }

    /**
     * Sets the value of the remarkId property.
     * 
     */
    public void setRemarkId(long value) {
        this.remarkId = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentResponseType }
     * 
     * 
     */
    public List<AttachmentResponseType> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<AttachmentResponseType>();
        }
        return this.attachment;
    }

}
