//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The RetryOrderRequest is used to retry an
 *                 order or a collection of order components for a given
 *                 order. When retrying an order or a collection of order
 *                 components, all failed tasks in the order or within the
 *                 order components will be retried and transitioned back
 *                 to the normal execution modes such as do, redo and undo
 *                 from the failed execution modes.
 * 
 * <p>Java class for RetryOrderRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetryOrderRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xmlns.oracle.com/communications/ordermanagement}SimpleOrchestrationOrderRequestType"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetryOrderRequestType")
public class RetryOrderRequestType
    extends SimpleOrchestrationOrderRequestType
{


}
