//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Common base type for operations that
 *                 perform a state transition where an order ID or a
 *                 collection of order components are allowed. 
 * 
 * <p>Java class for SimpleOrchestrationOrderRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleOrchestrationOrderRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://xmlns.oracle.com/communications/ordermanagement}SimpleOrderStateTransitionRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderComponent" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderComponentReferenceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleOrchestrationOrderRequestType", propOrder = {
    "orderComponent"
})
@XmlSeeAlso({
    RetryOrderRequestType.class,
    ResolveFailureRequestType.class
})
public abstract class SimpleOrchestrationOrderRequestType
    extends SimpleOrderStateTransitionRequestType
{

    @XmlElement(name = "OrderComponent")
    protected OrderComponentReferenceType orderComponent;

    /**
     * Gets the value of the orderComponent property.
     * 
     * @return
     *     possible object is
     *     {@link OrderComponentReferenceType }
     *     
     */
    public OrderComponentReferenceType getOrderComponent() {
        return orderComponent;
    }

    /**
     * Sets the value of the orderComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderComponentReferenceType }
     *     
     */
    public void setOrderComponent(OrderComponentReferenceType value) {
        this.orderComponent = value;
    }

}
