//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DELETE_ORDER"/&gt;
 *     &lt;enumeration value="UPDATE_ORDER"/&gt;
 *     &lt;enumeration value="RAISE_EXCEPTION"/&gt;
 *     &lt;enumeration value="PROCESS_TASK"/&gt;
 *     &lt;enumeration value="SUSPEND_ORDER"/&gt;
 *     &lt;enumeration value="RESUME_ORDER"/&gt;
 *     &lt;enumeration value="SUBMIT_AMENDMENT"/&gt;
 *     &lt;enumeration value="CANCEL_ORDER"/&gt;
 *     &lt;enumeration value="PROCESS_AMENDMENT"/&gt;
 *     &lt;enumeration value="COPY_ORDER"/&gt;
 *     &lt;enumeration value="COMPENSATE_TASK"/&gt;
 *     &lt;enumeration value="FAIL_ORDER"/&gt;
 *     &lt;enumeration value="ABORT_ORDER"/&gt;
 *     &lt;enumeration value="MANAGE_ORDER_FALLOUT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TransactionType")
@XmlEnum
public enum TransactionType {

    DELETE_ORDER,
    UPDATE_ORDER,
    RAISE_EXCEPTION,
    PROCESS_TASK,
    SUSPEND_ORDER,
    RESUME_ORDER,
    SUBMIT_AMENDMENT,
    CANCEL_ORDER,
    PROCESS_AMENDMENT,
    COPY_ORDER,
    COMPENSATE_TASK,
    FAIL_ORDER,
    ABORT_ORDER,
    MANAGE_ORDER_FALLOUT;

    public String value() {
        return name();
    }

    public static TransactionType fromValue(String v) {
        return valueOf(v);
    }

}
