//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *     An empty response with no errors
 *                 signals a successful    updates. If a remark was part of
 *                 the update, the    response includes the id of the
 *                 remark and if applicable    the id and filename of the attachment.
 * 
 * <p>Java class for UpdateOrderResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateOrderResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderId" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderIdType"/&gt;
 *         &lt;element name="Remark" type="{http://xmlns.oracle.com/communications/ordermanagement}RemarkResponseType" minOccurs="0"/&gt;
 *         &lt;element name="State" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType"/&gt;
 *         &lt;element name="TargetState" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderStateType" minOccurs="0"/&gt;
 *         &lt;element name="Data" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderDataType" minOccurs="0"/&gt;
 *         &lt;element name="AmendmentSummary" type="{http://xmlns.oracle.com/communications/ordermanagement}AmendmentSummaryType" minOccurs="0"/&gt;
 *         &lt;element name="OrderAlreadyStartedWarning" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateOrderResponseType", propOrder = {
    "orderId",
    "remark",
    "state",
    "targetState",
    "data",
    "amendmentSummary",
    "orderAlreadyStartedWarning"
})
public class UpdateOrderResponseType {

    @XmlElement(name = "OrderId", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String orderId;
    @XmlElement(name = "Remark")
    protected RemarkResponseType remark;
    @XmlElement(name = "State", required = true)
    @XmlSchemaType(name = "string")
    protected OrderStateType state;
    @XmlElement(name = "TargetState")
    @XmlSchemaType(name = "string")
    protected OrderStateType targetState;
    @XmlElement(name = "Data")
    protected OrderDataType data;
    @XmlElement(name = "AmendmentSummary")
    protected AmendmentSummaryType amendmentSummary;
    @XmlElement(name = "OrderAlreadyStartedWarning")
    protected OrderAlreadyStartedWarning orderAlreadyStartedWarning;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link RemarkResponseType }
     *     
     */
    public RemarkResponseType getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemarkResponseType }
     *     
     */
    public void setRemark(RemarkResponseType value) {
        this.remark = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link OrderStateType }
     *     
     */
    public OrderStateType getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderStateType }
     *     
     */
    public void setState(OrderStateType value) {
        this.state = value;
    }

    /**
     * Gets the value of the targetState property.
     * 
     * @return
     *     possible object is
     *     {@link OrderStateType }
     *     
     */
    public OrderStateType getTargetState() {
        return targetState;
    }

    /**
     * Sets the value of the targetState property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderStateType }
     *     
     */
    public void setTargetState(OrderStateType value) {
        this.targetState = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDataType }
     *     
     */
    public OrderDataType getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDataType }
     *     
     */
    public void setData(OrderDataType value) {
        this.data = value;
    }

    /**
     * Gets the value of the amendmentSummary property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentSummaryType }
     *     
     */
    public AmendmentSummaryType getAmendmentSummary() {
        return amendmentSummary;
    }

    /**
     * Sets the value of the amendmentSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentSummaryType }
     *     
     */
    public void setAmendmentSummary(AmendmentSummaryType value) {
        this.amendmentSummary = value;
    }

    /**
     * Gets the value of the orderAlreadyStartedWarning property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAlreadyStartedWarning }
     *     
     */
    public OrderAlreadyStartedWarning getOrderAlreadyStartedWarning() {
        return orderAlreadyStartedWarning;
    }

    /**
     * Sets the value of the orderAlreadyStartedWarning property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAlreadyStartedWarning }
     *     
     */
    public void setOrderAlreadyStartedWarning(OrderAlreadyStartedWarning value) {
        this.orderAlreadyStartedWarning = value;
    }


    /**
     *        Used when update tried
     *                             to start the order which is already started
     *                             the order process flow.
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OrderAlreadyStartedWarning {


    }

}
