//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.28 at 04:23:36 PM IST 
//


package rogers.utility.app.service.osmws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for UpdateOrderRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateOrderRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderId" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderIdType"/&gt;
 *         &lt;element name="View" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType"/&gt;
 *         &lt;element name="ResponseView" type="{http://xmlns.oracle.com/communications/ordermanagement}EntityNameType" minOccurs="0"/&gt;
 *         &lt;element name="OrderDataFilter" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderDataFilterType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="UpdatedOrder" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderDataType" minOccurs="0"/&gt;
 *           &lt;element name="UpdatedNodes" type="{http://xmlns.oracle.com/communications/ordermanagement}OrderDataType" minOccurs="0"/&gt;
 *           &lt;element name="DataChange" type="{http://xmlns.oracle.com/communications/ordermanagement}DataChangeRequestType" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="StartOrder" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Remark" type="{http://xmlns.oracle.com/communications/ordermanagement}CreateRemarkType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateOrderRequestType", propOrder = {
    "orderId",
    "view",
    "responseView",
    "orderDataFilter",
    "updatedOrder",
    "updatedNodes",
    "dataChange",
    "startOrder",
    "remark"
})
public class UpdateOrderRequestType {

    @XmlElement(name = "OrderId", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String orderId;
    @XmlElement(name = "View", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String view;
    @XmlElement(name = "ResponseView")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String responseView;
    @XmlElement(name = "OrderDataFilter")
    protected OrderDataFilterType orderDataFilter;
    @XmlElement(name = "UpdatedOrder")
    protected OrderDataType updatedOrder;
    @XmlElement(name = "UpdatedNodes")
    protected OrderDataType updatedNodes;
    @XmlElement(name = "DataChange")
    protected DataChangeRequestType dataChange;
    @XmlElement(name = "StartOrder", defaultValue = "false")
    protected Boolean startOrder;
    @XmlElement(name = "Remark")
    protected CreateRemarkType remark;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getView() {
        return view;
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setView(String value) {
        this.view = value;
    }

    /**
     * Gets the value of the responseView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseView() {
        return responseView;
    }

    /**
     * Sets the value of the responseView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseView(String value) {
        this.responseView = value;
    }

    /**
     * Gets the value of the orderDataFilter property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDataFilterType }
     *     
     */
    public OrderDataFilterType getOrderDataFilter() {
        return orderDataFilter;
    }

    /**
     * Sets the value of the orderDataFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDataFilterType }
     *     
     */
    public void setOrderDataFilter(OrderDataFilterType value) {
        this.orderDataFilter = value;
    }

    /**
     * Gets the value of the updatedOrder property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDataType }
     *     
     */
    public OrderDataType getUpdatedOrder() {
        return updatedOrder;
    }

    /**
     * Sets the value of the updatedOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDataType }
     *     
     */
    public void setUpdatedOrder(OrderDataType value) {
        this.updatedOrder = value;
    }

    /**
     * Gets the value of the updatedNodes property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDataType }
     *     
     */
    public OrderDataType getUpdatedNodes() {
        return updatedNodes;
    }

    /**
     * Sets the value of the updatedNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDataType }
     *     
     */
    public void setUpdatedNodes(OrderDataType value) {
        this.updatedNodes = value;
    }

    /**
     * Gets the value of the dataChange property.
     * 
     * @return
     *     possible object is
     *     {@link DataChangeRequestType }
     *     
     */
    public DataChangeRequestType getDataChange() {
        return dataChange;
    }

    /**
     * Sets the value of the dataChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataChangeRequestType }
     *     
     */
    public void setDataChange(DataChangeRequestType value) {
        this.dataChange = value;
    }

    /**
     * Gets the value of the startOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStartOrder() {
        return startOrder;
    }

    /**
     * Sets the value of the startOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStartOrder(Boolean value) {
        this.startOrder = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link CreateRemarkType }
     *     
     */
    public CreateRemarkType getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateRemarkType }
     *     
     */
    public void setRemark(CreateRemarkType value) {
        this.remark = value;
    }

}
